"""
core/pyinstaller_runner.py

Responsible for:
- Executing PyInstaller builds using a generated spec file.
- Streaming stdout/stderr to the GUI log panel.
- Providing a structured BuildResult object.
- Handling OS-specific build flags.
- Ensuring clean, predictable build behavior.

This module is intentionally:
- Backend-only (no GUI imports).
- Resilient (PyInstaller errors become structured results).
- Compatible with Windows, Linux, and macOS.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional, Callable
import subprocess
import sys
import logging
import os
import shutil
import time

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class BuildResult:
    """
    Represents the outcome of a PyInstaller build.

    Fields:
    - success: True if build completed without fatal errors
    - spec_file: path to the generated spec file
    - dist_path: path to the dist/ output directory
    - build_path: path to the build/ directory
    - warnings: non-fatal issues (missing DLLs, PyInstaller warnings)
    - errors: fatal issues (PyInstaller crash, missing entry point)
    - duration_seconds: total build time
    """
    success: bool
    spec_file: str
    dist_path: str
    build_path: str
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    duration_seconds: float = 0.0


# ---------------------------------------------------------------------------
# PyInstallerRunner – public API
# ---------------------------------------------------------------------------

class PyInstallerRunner:
    """
    Executes PyInstaller builds using a spec file.

    Responsibilities:
    - Validate environment (PyInstaller installed?)
    - Run PyInstaller with correct flags
    - Stream logs to a callback (GUI log panel)
    - Return a structured BuildResult

    The GUI will call:
        runner = PyInstallerRunner()
        result = runner.build(spec_file, log_callback)
    """

    def __init__(self, python_executable: Optional[str] = None) -> None:
        self.python_executable = python_executable or sys.executable

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def build(
        self,
        spec_file: str,
        log_callback: Optional[Callable[[str], None]] = None,
        clean: bool = True,
        noconfirm: bool = True,
    ) -> BuildResult:
        """
        Execute a PyInstaller build using the given spec file.

        :param spec_file: Path to the spec file generated by spec_generator.py
        :param log_callback: Function that receives log lines (GUI log panel)
        :param clean: Whether to run PyInstaller with --clean
        :param noconfirm: Whether to run PyInstaller with --noconfirm
        :return: BuildResult
        """
        start_time = time.time()
        warnings: List[str] = []
        errors: List[str] = []

        if not os.path.exists(spec_file):
            msg = f"Spec file not found: {spec_file}"
            logger.error(msg)
            errors.append(msg)
            return BuildResult(
                success=False,
                spec_file=spec_file,
                dist_path="",
                build_path="",
                warnings=warnings,
                errors=errors,
                duration_seconds=0.0,
            )

        if not self._pyinstaller_available():
            msg = "PyInstaller is not installed in this environment."
            logger.error(msg)
            errors.append(msg)
            return BuildResult(
                success=False,
                spec_file=spec_file,
                dist_path="",
                build_path="",
                warnings=warnings,
                errors=errors,
                duration_seconds=0.0,
            )

        cmd = [
            self.python_executable,
            "-m",
            "PyInstaller",
            spec_file,
        ]

        if clean:
            cmd.append("--clean")
        if noconfirm:
            cmd.append("--noconfirm")

        logger.info("Running PyInstaller: %s", " ".join(cmd))
        if log_callback:
            log_callback(f"[INFO] Running PyInstaller: {' '.join(cmd)}")

        # Execute PyInstaller as subprocess
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
        )

        # Stream logs line-by-line
        for stream, prefix in [(process.stdout, ""), (process.stderr, "[ERR] ")]:
            if stream is None:
                continue
            for line in stream:
                line = line.rstrip()
                if not line:
                    continue

                # Detect warnings
                if "warning" in line.lower():
                    warnings.append(line)

                # Detect errors
                if "error" in line.lower() or "failed" in line.lower():
                    errors.append(line)

                # Send to GUI
                if log_callback:
                    log_callback(prefix + line)

        process.wait()
        duration = time.time() - start_time

        # Determine output paths
        dist_path = self._find_dist_path(spec_file)
        build_path = self._find_build_path(spec_file)

        success = process.returncode == 0 and not errors

        return BuildResult(
            success=success,
            spec_file=spec_file,
            dist_path=dist_path,
            build_path=build_path,
            warnings=warnings,
            errors=errors,
            duration_seconds=duration,
        )

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #

    def _pyinstaller_available(self) -> bool:
        """Check if PyInstaller is installed."""
        try:
            subprocess.run(
                [self.python_executable, "-m", "PyInstaller", "--version"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=True,
            )
            return True
        except Exception:
            return False

    def _find_dist_path(self, spec_file: str) -> str:
        """Return the dist/ directory path based on the spec file location."""
        base = os.path.dirname(spec_file)
        return os.path.join(base, "dist")

    def _find_build_path(self, spec_file: str) -> str:
        """Return the build/ directory path based on the spec file location."""
        base = os.path.dirname(spec_file)
        return os.path.join(base, "build")


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------

def run_pyinstaller(spec_file: str, log_callback: Optional[Callable[[str], None]] = None) -> BuildResult:
    """
    Convenience wrapper for simple usage.

    Example:
        result = run_pyinstaller("build/pandas.spec", print)
    """
    runner = PyInstallerRunner()
    return runner.build(spec_file, log_callback)
