"""
gui/build_report_window.py

Dependency Summary viewer panel for PyDependencyInspector.

Updated to:
- Display the HTML dependency summary generated by BuildReportGenerator.
- Remove PyInstaller/build terminology.
- Provide a clean, dark-themed HTML viewer.
- GUI-only (no logic).

This module is intentionally:
- Modular.
- Read-only.
- Driven by ProjectState.
"""

from __future__ import annotations

from PySide6.QtWidgets import (
    QWidget,
    QVBoxLayout,
    QLabel,
    QTextBrowser,
    QSizePolicy,
)
from PySide6.QtCore import Qt

from ..utils.logging_utils import get_logger

logger = get_logger(__name__)


class BuildReportWindow(QWidget):
    """
    Displays the dependency summary HTML.
    """

    def __init__(self, project_state) -> None:
        super().__init__()
        self.project_state = project_state

        self._init_ui()
        self._apply_styles()

    # ------------------------------------------------------------------ #
    # UI initialization
    # ------------------------------------------------------------------ #

    def _init_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(12, 12, 12, 12)
        layout.setSpacing(8)

        self.title_label = QLabel("Dependency Summary")
        self.title_label.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.title_label.setStyleSheet("font-size: 20px; font-weight: 600;")

        self.browser = QTextBrowser()
        self.browser.setOpenExternalLinks(True)
        self.browser.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        layout.addWidget(self.title_label)
        layout.addWidget(self.browser)

    # ------------------------------------------------------------------ #
    # Styling
    # ------------------------------------------------------------------ #

    def _apply_styles(self) -> None:
        self.setStyleSheet("""
            QLabel {
                color: #80cbc4;
            }
            QTextBrowser {
                background-color: #1a1a1a;
                color: #e0e0e0;
                border: 1px solid #333;
                padding: 8px;
                font-size: 13px;
            }
            QTextBrowser a {
                color: #4fc3f7;
            }
            QTextBrowser a:hover {
                color: #81d4fa;
            }
        """)

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def update_report(self, report) -> None:
        """
        Update the panel with a new BuildReport object.
        """
        if not report:
            self.browser.setHtml("<p><em>No dependency summary available.</em></p>")
            return

        logger.info("Updating Dependency Summary panel for project '%s'", report.project_name)

        self.title_label.setText(f"Dependency Summary — {report.project_name}")

        # Build fragment HTML
        html = self._build_html(report)

        # Store for export
        self.project_state.build_report_html = html

        # Display in GUI
        self.browser.setHtml(html)

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #

    def _build_html(self, report) -> str:
        """
        Build fragment HTML for GUI display.
        No <html>, <head>, <body>, or <style>.
        """

        # Header
        header_html = f"""
            <h2>Dependency Summary — {report.project_name}</h2>
            <p><strong>Version:</strong> {report.version}</p>
            <p><strong>OS Profile:</strong> {report.os_profile}</p>
            <p><strong>Generated at:</strong> {report.generated_at}</p>
            <hr>
        """

        # Dependencies table
        deps_html = """
            <h3>Dependencies</h3>
            <table>
                <tr>
                    <th>Name</th>
                    <th>Version</th>
                    <th>Type</th>
                    <th>Summary</th>
                </tr>
        """

        for dep in report.dependencies:
            deps_html += f"""
                <tr>
                    <td>{dep.name}</td>
                    <td>{dep.version}</td>
                    <td>{dep.type}</td>
                    <td>{dep.summary}</td>
                </tr>
            """

        deps_html += "</table><hr>"

        # Warnings
        warnings_html = "<h3>Warnings</h3>"
        if report.warnings:
            warnings_html += "<ul>"
            for w in report.warnings:
                warnings_html += f"<li>{w}</li>"
            warnings_html += "</ul>"
        else:
            warnings_html += "<p><em>None</em></p>"

        # Errors
        errors_html = "<h3>Errors</h3>"
        if report.errors:
            errors_html += "<ul>"
            for e in report.errors:
                errors_html += f"<li>{e}</li>"
            errors_html += "</ul>"
        else:
            errors_html += "<p><em>None</em></p>"

        # Final fragment HTML
        return f"""
            {header_html}
            {deps_html}
            {warnings_html}
            {errors_html}
        """
