{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0d3a3987-1991-4f95-a167-5558ea871764",
   "metadata": {},
   "source": [
    "This is a comprehensive, notebook-ready Markdown explanation of the four major optimization techniques\n",
    "our GUI should support. Each section includes mathematical foundations, algorithmic steps, and illustrative examples.\n",
    "\n",
    "---\n",
    "\n",
    "# 📊 Linear Optimization Methods: Mathematical & Algorithmic Overview\n",
    "\n",
    "---\n",
    "\n",
    "## 1. 🔁 Simplex Method\n",
    "\n",
    "### 🧠 Concept\n",
    "The **Simplex Method** solves linear programs of the form:\n",
    "\n",
    "$$\\[\n",
    "\\text{Maximize } z = c^T x \\quad \\text{subject to } Ax \\leq b, \\quad x \\geq 0\n",
    "\\]$$\n",
    "\n",
    "It moves from one **vertex (basic feasible solution)** of the feasible region to another, improving the objective at each step.\n",
    "\n",
    "### ⚙️ Algorithm Steps\n",
    "1. Convert inequalities to equalities using **slack variables**.\n",
    "2. Set up the **initial tableau**.\n",
    "3. Identify the **entering variable** (most negative coefficient in objective row).\n",
    "4. Identify the **leaving variable** (minimum ratio test).\n",
    "5. Perform **pivoting** to update the tableau.\n",
    "6. Repeat until no negative coefficients remain in the objective row.\n",
    "\n",
    "### 📌 Example\n",
    "\n",
    "Maximize:  \n",
    "$$\\[\n",
    "z = 3x + 2y\n",
    "\\]$$  \n",
    "Subject to:  \n",
    "$$\\[\n",
    "x + y \\leq 4 \\\\\n",
    "x \\leq 2 \\\\\n",
    "x, y \\geq 0\n",
    "\\]$$\n",
    "\n",
    "Add slack variables $$\\( s_1, s_2 \\)$$, and solve using tableau iterations.\n",
    "\n",
    "---\n",
    "\n",
    "## 2. 🔄 Dual Simplex Method\n",
    "\n",
    "### 🧠 Concept\n",
    "The **Dual Simplex Method** is used when the solution is **dual feasible but primal infeasible**. It’s ideal for post-optimality analysis or\n",
    "when constraints change.\n",
    "\n",
    "### ⚙️ Algorithm Steps\n",
    "1. Start with a tableau where the objective is optimal but some RHS values are negative.\n",
    "2. Identify the **leaving variable** (most negative RHS).\n",
    "3. Identify the **entering variable** (minimum ratio of cost coefficient to pivot column).\n",
    "4. Pivot and update the tableau.\n",
    "5. Repeat until all RHS values are non-negative.\n",
    "\n",
    "### 📌 Example\n",
    "\n",
    "Suppose after adding a new constraint, your current solution violates feasibility. Dual simplex allows you to re-optimize without restarting\n",
    "from scratch.\n",
    "\n",
    "---\n",
    "\n",
    "## 3. 🧭 Dikin Method (Interior Point)\n",
    "\n",
    "### 🧠 Concept\n",
    "The **Dikin Method** is a primal interior-point algorithm. It uses a **log-barrier function** to stay within the feasible region and\n",
    "performs **Newton steps** to move toward optimality.\n",
    "\n",
    "### 🧮 Barrier Function\n",
    "\n",
    "$$\\[\n",
    "\\phi(x) = c^T x - \\sum_{i=1}^m \\log(b_i - A_i x)\n",
    "\\]$$\n",
    "\n",
    "### ⚙️ Algorithm Steps\n",
    "1. Start with a strictly feasible point $$\\( x_0 \\)$$.\n",
    "2. Compute gradient and Hessian of the barrier function.\n",
    "3. Solve Newton system:  \n",
    "$$\\[\n",
    "H \\Delta x = -\\nabla \\phi(x)\n",
    "\\]$$\n",
    "4. Perform line search to maintain feasibility.\n",
    "5. Update $$\\( x \\leftarrow x + \\alpha \\Delta x \\)$$.\n",
    "6. Repeat until convergence.\n",
    "\n",
    "### 📌 Example\n",
    "\n",
    "Maximize:  \n",
    "$$\\[\n",
    "z = x + y\n",
    "\\]$$  \n",
    "Subject to:  \n",
    "$$\\[\n",
    "x + y \\leq 2 \\\\\n",
    "x \\geq 0, y \\geq 0\n",
    "\\]$$\n",
    "\n",
    "Start at $$\\( x = y = 1 \\)$$, compute slack, gradient, Hessian, and iterate.\n",
    "\n",
    "---\n",
    "\n",
    "## 4. 🔢 Integer Linear Programming (ILP)\n",
    "\n",
    "### 🧠 Concept\n",
    "ILP solves linear programs where **some or all variables must be integers**. The feasible region becomes **discrete**, \n",
    "and the problem is **NP-hard**.\n",
    "\n",
    "### ⚙️ Common Algorithms\n",
    "- **Branch and Bound**: Recursively split the problem into subproblems.\n",
    "- **Cutting Planes**: Add constraints to eliminate fractional solutions.\n",
    "- **Heuristics**: Greedy or randomized methods for large-scale ILPs.\n",
    "\n",
    "### 📌 Example\n",
    "\n",
    "Maximize:  \n",
    "$$\\[\n",
    "z = 5x + 3y\n",
    "\\]$$  \n",
    "Subject to:  \n",
    "$$\\[\n",
    "2x + y \\leq 7 \\\\\n",
    "x, y \\in \\mathbb{Z}_{\\geq 0}\n",
    "\\]$$\n",
    "\n",
    "Try $$\\( x = 3, y = 1 \\Rightarrow z = 18 \\)$$, check feasibility, and explore other integer combinations.\n",
    "\n",
    "---\n",
    "\n",
    "## 🧮 Summary Table\n",
    "\n",
    "| Method           | Feasibility Required | Variable Type | Use Case                          |\n",
    "|------------------|----------------------|----------------|-----------------------------------|\n",
    "| Simplex          | Primal feasible      | Continuous     | Standard LP                       |\n",
    "| Dual Simplex     | Dual feasible        | Continuous     | Constraint updates, post-optimal |\n",
    "| Dikin            | Strictly feasible    | Continuous     | Interior-point, smooth problems  |\n",
    "| ILP              | Discrete feasible    | Integer         | Scheduling, routing, allocation  |\n",
    "\n",
    "---"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "SoS",
   "language": "sos",
   "name": "sos"
  },
  "language_info": {
   "codemirror_mode": "sos",
   "file_extension": ".sos",
   "mimetype": "text/x-sos",
   "name": "sos",
   "nbconvert_exporter": "sos_notebook.converter.SoS_Exporter",
   "pygments_lexer": "sos"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
